### PR TITLE
Add gzip command

### PR DESCRIPTION
**Pull request by ajwalkiewicz**
Adding gzip.md

### CODE REVIEW

**Comment by srsudar** [comment]
Nice thanks! I'm a bit behind on merging stuff but will incorporate this into the next release.

**Comment by ajwalkiewicz** [comment]
Thanks :) 
It's been couple of months. We should we expect next release? :)

**Review by EmilySeville7cfg — APPROVED** [review]

**Comment by srsudar** [comment]
Hey guys! Sorry about the delay, been a wild time lately. I'm traveling tomorrow and will try to take a look at this then and get a release out in the next week.

**Comment by srsudar** [comment]
This looks great, thanks! Good job on the formatting too. =D

Can you make this change for some spelling/grammar stuff?

This:

> `gzip` by default delete the file that is beeing compressed or decompressed. To keep the original file use `--keep` flag.

to:

> `gzip` by default deletes the file that is being compressed or decompressed. To keep the original file use the `--keep` flag.

**Comment by ajwalkiewicz** [comment]
Sorry for delay, I corrected that line.

**Comment by srsudar** [comment]
My apologies again for the delay on this. I just released as part of `1.2.2`. Let me know if anything looks amiss.

Thank you for bearing with me as I delayed, and thank you for contributing!

**Pull request merged**
