### PR TITLE
Amend punctuation and capitalization for each section

### PR DESCRIPTION
**Pull request by scorphus**
While revising `git` example, I noticed many of the examples lack what seems to be a pattern, which I think is made consistent with this pull request. Please review and comment.

### CODE REVIEW

**Comment by srsudar** [comment]
That is an interesting point. My original thought was to leave out colons in the first set of examples just to try and keep things especially terse. The first section commands aren't capitalized, either. I am partial to keeping a no capitalization, minimal punctuation approach to the first section. I just tried a few and for some reason I found it easier to read quickly, but it could be in my head. What do you think?

For all the examples outside of the first section, I completely agree they have colons. Good catch!

**Comment by srsudar** [comment]
Thinking about this some more, I'm inclined to leaving out the capitalization and colons in the first section. I think of that section as the place to go to for quick scanning. I was going to say that people recognize words based on shape, and that punctuation can confuse that shape. Which might be why I **think** I find it easier to scan and parse the top examples without the colons. [This site](https://www.microsoft.com/typography/ctfonts/WordRecognition.aspx) makes me question that somewhat, however. Interesting all the same. [This](http://www.dummies.com/how-to/content/how-recognizing-the-shapes-of-words-aids-speed-rea.html) much less rigorous Dummies site has some other interesting examples of reading based on shape.

**Comment by scorphus** [comment]
I just had time to read those interesting articles, thanks for sharing! However, before reading them, I had already agreed with you that the lack of capitalization and punctuation makes it more easy to skim through. I'm gonna translate that into an amend to this change.

**Comment by srsudar** [comment]
Perfect. I'm happy to just pull in the relevant changes if you'd like. I'll do a release afterwards. I'm trying to move to a monthly release schedule to keep on top of things.

**Comment by scorphus** [comment]
Dear @srsudar, now I think this is just right, for each and every section. But please verify, my regex may have missed something.

**Comment by srsudar** [comment]
Both this and #58 are great, thank you very much.

What was the regex you used to find all these? I've just been going by hand.

**Comment by scorphus** [comment]
I'm glad to contribute!

I used upper/lower/etc variations of the following regex – surrounded by double-quotes – to match most of the amendable sentences:
```
"(^[A-Z][^:\n]+?)((\n^[^:\n]+?)*)[ \.]*\n\n    "
```
And the replacement expression:
```
"$1$2:\n\n    "
```

**Pull request merged**
